### ISSUE TITLE
Week 8 - Review Our App

### ISSUE THREAD

**Issue by egs104** [KickSwap/Bred1s-iOS#18]
We have completed 33% of the required functionality of our app. Parts of our app use the camera so testing on a simulator will cause the app to crash. Also, we were wondering what tools we can use to create GIFs of our app running on our actual device. Thanks! /cc @codepathreview

**Comment by minhkhang1795** [comment]
Wow, great!! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.

**Comment by minhkhang1795** [comment]
For the gif file, you can google for the app. Maybe try [this one](http://www.pocket-lint.com/news/129760-how-to-make-animated-gifs-directly-from-your-smartphone)

If nothing works, you should run your app on your simulator and use LiceCap to create a gif file :+1:

p/s: Please update the gif file as soon as possible
